### PR TITLE
Allow parsing credentials from string

### LINKED ISSUE #9: Allow passing credentials object instead of a path. Or credentials json string.
Currently there should be a mounted file with credentials for the library to work. This is inconvenient in case the credentials are passed using an environment variable. I'm about to make a fork to fix this, but not sure the solution would be proper enough to contribute.

### PR DESCRIPTION
**Pull request by ruseinov**
Fixes #9

### CODE REVIEW

**Comment by ruseinov** [comment]
@kayleg please take a look when you have a chance.

**Comment by kayleg** [comment]
Thanks for adding this. I like the concept, just not entirely sold on the function name. I feel like the name should be more descriptive without needing to check the argument name (especially since the 2 `new` functions take the same type), but I can't come up with a better suggestion at the moment.

**Comment by ruseinov** [comment]
new_with_credentials?

**Comment by ruseinov** [comment]
Here is a list of options I could come up with:
new_with_crdentials
new_with_json
new_with_json_string
from_json

**Comment by ruseinov** [comment]
I’d vote for from_json actually

**Comment by ruseinov** [comment]
Ended up with `from_string`.

**Comment by kayleg** [comment]
good enough for now

**Pull request merged**
