### PR TITLE
feature: Add attributes to published EncodedMessage

### PR DESCRIPTION
**Pull request by BigJerBD**
Feel free to ask/do anything with this PR,  I'll try to help if I can :) 

related issue : https://github.com/kayleg/cloud-pubsub/issues/19

### CODE REVIEW

**Comment by kayleg** [comment]
Should attributes on the `EncodedMessage` be an `Option`?
From a performance stance, there's no need to allocate and serialize empty options.

Let me know if I'm missing something but otherwise that would be the only change.

**Comment by BigJerBD** [comment]
Alright I'll do it when I have a little bit of time :)

**Comment by BigJerBD** [comment]
Update done feel free to review and merge :)

**Review by kayleg — APPROVED** [review]
LGTM

**Pull request merged**
